### PR TITLE
fix: use case line breaks

### LINKED ISSUE #213: Missing line breaks in use case diagrams
### Describe the bug

It seems that line breaks are not possible for use case diagrams.

#### To Reproduce

1. Create a use case diagram
2. Add a use case that exceeds the limit

#### Expected behavior

If the text gets too long, I expect a line break like in other diagrams :thinking: 

#### Screenshots

image

### Environment

<details><pre>
 - OS: Linux
 - Browser: Chromium, Firefox
 - Version 1.3.8
</pre></details>

### PR DESCRIPTION
**Pull request by tamang29**
### Checklist

- [x] I linked PR with a related issue
- [x] I added multiple screenshots/screencasts of my UI changes

### Motivation and Context
The text in UseCase Diagram's usecase node doesnt have a line break causing the text to overflow in x.

This PR completes #213

### Steps for Testing

1. Create a UseCase diagram
2. Add use-case element
3. Rename the usecase

### Screenshots

https://github.com/user-attachments/assets/ac64b93f-32a0-4658-be43-551bb031c648

### CODE REVIEW

**Review by FelixTJDietrich — CHANGES_REQUESTED** [review]
It is still possible to have the text overlap the outline, I think we could be a bit smarter with the layout:
Image
Image

Have you seen the new hyped pretext library? 
https://github.com/chenglou/pretext
Maybe it could help 😎

File: library/lib/components/svgs/nodes/useCaseDiagram/UseCaseNodeSVG.tsx [hunk 1]
```diff
@@ -6,11 +6,35 @@ import AssessmentIcon from "../../AssessmentIcon"
 import { SVGComponentProps } from "@/types/SVG"
 import { DefaultNodeProps } from "@/types"
 import { getCustomColorsFromData } from "@/utils/layoutUtils"
+import { useMemo } from "react"
```
Comment (FelixTJDietrich) [inline library/lib/components/svgs/nodes/useCaseDiagram/UseCaseNodeSVG.tsx:9]: We should upgrade to react 19 with react compiler soon so we don't need to manually memoize as often 🤔

**Review by FelixTJDietrich — APPROVED** [review]
We can merge it as a first step, I'm trying a follow-up with the pretext library.
