### PR TITLE
Fix wrong package size on export

### LINKED ISSUE #146: Exported diagrams have wrong package size
### Describe the bug
When exporting an UML diagram by using the built-in export functionality (_Export_ -> _As PNG_ or _As SVG_, issue occurs in both cases), the exported file (png/svg) shows the packages in a wrong size. They become significantly bigger than shown in the editor. The preview in the editor, however, does not change. Also, the exported JSON of the displayed diagram seems to reflect the correct sizes, as importing the file in a new editor instance results in the initial, correct diagram.

#### To Reproduce
I had the impression that apollon adjusts the package sizes to fill the browser window. However, I am not sure about that.
1. Create any kind of diagram containing a package. 
2. Export the diagram via _Export_ -> _As PNG_.

#### Expected behavior
I expect that the exported diagram looks equal to the one shown in the apollon editor and that sizes or proportions do not change.

#### Screenshots
This is how an example diagram is shown in the apollon editor (screenshot):
Screenshot Apollon Editor

This is how the exported png looks like:
Exported Diagram

### Environment
<details><pre>
 - OS: macOS 11.0.1
 - Browser: Safari 14.0.1.
 - 38' monitor
</pre></details>

### PR DESCRIPTION
**Pull request by iozbeyli**
### Checklist
- [x] I added multiple screenshots/screencasts of my UI changes

### Description
Fixes #146 

### Steps for Testing
1. Create a class diagram with two packages side by side
2. Exported package should keep its size
3. Try exporting all the other elements to be sure nothing breaks

#### On editor
Screen Shot 2021-02-26 at 02 07 53

#### Before

Screen Shot 2021-02-26 at 02 10 00

#### After

Screen Shot 2021-02-26 at 02 08 07

### CODE REVIEW

**Review by ivanchimeno — APPROVED** [review]

**Review by SimonEntholzer — APPROVED** [review]

File: src/main/scenes/svg.tsx [hunk 1]
```diff
@@ -86,28 +86,12 @@ const getInitialState = ({ model, options }: Props): State => {
...
-      if (!original) {
-        return x;
-      }
-      x.bounds.x = original.bounds.x;
-      x.bounds.y = original.bounds.y;
-      return x;
-    });
+    const [root, ...updates] = element.render(layer, []) as UMLElement[];
 
     return [root, ...updates];
```
Comment (FrankeLukas) [inline src/main/scenes/svg.tsx:91]: I guess this could simplify to `return element.render(layer, []) as UMLElement[];` but it's not really important.

**Review by FrankeLukas — APPROVED** [review]
Lgtm.
